name: Testing

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  BuildAndRun:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Dependencies
      run: sudo apt update; sudo apt install libgtest-dev

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Run Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./tests/physen.gtest
